{
 "title": "Zamza",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zamza_processed_messages{}[1m]))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(rate(zamza_processed_messages_success{}[1m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Kafka Consume Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zamza_processed_messages{}[1m]))-sum(rate(zamza_processed_messages_success{}[1m]))",
     "legendFormat": "Difference"
    }
   ]
  },
  {
   "title": "API Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zamza_api_calls{}[1m]))",
     "legendFormat": "Calls"
    }
   ]
  },
  {
   "title": "Message Processing Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zamza_processed_message_ms_gauge",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Topic Changes 2 hours",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zamza_configured_topics_changed{}[2h]))",
     "legendFormat": "Configured"
    },
    {
     "expr": "sum(rate(zamza_discovered_topics_changed{}[2h]))",
     "legendFormat": "Discovered"
    }
   ]
  },
  {
   "title": "HTTP Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zamza_http_calls{}[1m]))",
     "legendFormat": "Calls"
    }
   ]
  },
  {
   "title": "Clean Up Job Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "zamza_job_clean_up_ms_gauge", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Pagination Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zamza_mongo_keyindex_paginate_ms_gauge",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Configured Topics",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(zamza_configured_topics_gauge)"
    }
   ]
  },
  {
   "title": "Insert Performance Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zamza_mongo_keyindex_insert_ms_gauge",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Upsert Performance Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zamza_mongo_keyindex_upsert_ms_gauge",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Key Lookups Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zamza_mongo_keyindex_find_key_ms_gauge",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Pagination Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zamza_mongo_keyindex_paginate_ms_gauge",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Clean Up Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zamza_job_clean_up_ran{}[5m]))",
     "legendFormat": "Runs"
    },
    {
     "expr": "sum(rate(zamza_job_clean_up_ran_success{}[5m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Kafka Message Types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zamza_processed_messages_compact{}[1m]))",
     "legendFormat": "Compacts"
    },
    {
     "expr": "sum(rate(zamza_processed_messages_delete{}[1m]))",
     "legendFormat": "Deletes"
    },
    {
     "expr": "sum(rate(zamza_processed_messages_none{}[1m]))",
     "legendFormat": "Nones"
    }
   ]
  },
  {
   "title": "Kafka Tombstones 5 min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zamza_processed_messages_tombstone{}[5m]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Poll Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zamza_job_poll_ran{}[5m]))",
     "legendFormat": "Runs"
    },
    {
     "expr": "sum(rate(zamza_job_poll_ran_success{}[5m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Discover Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zamza_job_discover_ran{}[5m]))",
     "legendFormat": "Runs"
    },
    {
     "expr": "sum(rate(zamza_job_discover_ran_success{}[5m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Access Control 15 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zamza_access_good{}[15m]))",
     "legendFormat": "Good"
    },
    {
     "expr": "sum(rate(zamza_access_bad{}[15m]))",
     "legendFormat": "Bad"
    }
   ]
  }
 ]
}